artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://elasticbeanstalk-eu-west-2-854337983934.s3.eu-west-2.amazonaws.com/ChickenDiseaseData.zip
  local_data_file: artifacts/data_ingestion/ChickenDiseaseData.zip
  unzip_dir: artifacts/data_ingestion
